build:
	docker build -t tangsengdaodaojsbridge .
deploy:
	docker build -t tangsengdaodaojsbridge  .
	docker tag tangsengdaodaojsbridge registry.cn-shanghai.aliyuncs.com/wukongim/tangsengdaodaojsbridge:latest
	docker push registry.cn-shanghai.aliyuncs.com/wukongim/tangsengdaodaojsbridge:latest